services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: tutorial-backend
    restart: always
    # environment:
    #   WAIT_HOSTS: postgres:5432
    # depends_on:
    #   - postgres
    ports:
      - 3000:3000
    networks:
      - tutorial-network
    # #fix nitro worker eaddrinuse
    # tmpfs:
    #   - /tmp
  nginx:
    image: nginx:mainline-alpine
    container_name: tutorial-nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - tutorial-network
    ports:
      - 80:80
    restart: unless-stopped
#   postgres:
#     image: public.ecr.aws/docker/library/postgres:latest
#     container_name: postgres
#     volumes:
#       - workflow-postgres-data:/var/lib/postgres/data
#     environment:
#       POSTGRES_PASSWORD: secret
#       POSTgRES_USER: postgres
#       POSTGRES_DB: workflow

# volumes:
#   workflow-postgres-data:

networks:
  tutorial-network:
    driver: bridge